[package]
name = "csqrl/colour-utils"
description = "Colour manipulation utility for Roblox"
version = "1.0.3"
license = "MIT"
authors = ["csqrl (https://github.com/csqrl)"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dev-dependencies]
TestEZ = "roblox/testez@^0.4.1"
