[package]
name = "csqrl/colour-utils"
description = "Colour manipulation utility for Roblox"
version = "1.3.0"
license = "MIT"
authors = ["csqrl (https://github.com/csqrl)"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = ["**"]
include = ["src", "src/**", "wally.toml", "wally.lock", "default.project.json"]
