name: Publish Release

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup Node 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install Roblox-TS
        run: |
          npm i -g roblox-ts
          npm i

      - name: Setup Toolchain
        uses: Roblox/setup-foreman@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set Project Name
        run: |
          PROJECT_NAME="colour-utils"
          echo "PROJECT_NAME=$PROJECT_NAME" >> $GITHUB_ENV

      - name: Build Project
        run: |
          rojo build default.project.json -o dist/${{ env.PROJECT_NAME }}.rbxm

      - name: Publish to NPM
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}

      - name: Upload to Roblox
        run: rojo upload default.project.json --asset_id 6573728888 --cookie ${{ secrets.ROBLOSECURITY }}
